{% set name = "careamics" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/careamics-{{ version }}.tar.gz
  sha256: a1261fa0d552fd0d8fe0a956c64525957fd80fdd0906ef112028f9eeefaf030e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy <2.0.0
    - pytorch >=2.0,<=2.5.1
    - torchvision <=0.20.1
    - bioimageio.core ==0.7
    - tifffile <=2024.12.12
    - pillow <=11.0.0
    - psutil <=6.1
    - pydantic >=2.5,<2.11
    - pytorch-lightning >=2.2,<=2.4
    - pyyaml <=6.0.2,!=6.0.0
    - typer ==0.15.1
    - scikit-image <=0.25.0
    - zarr <3.0.0

test:
  imports:
    - careamics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://careamics.github.io
  summary: Deep-learning library for running N2V and friends.
  description: |
    CAREamics is a PyTorch library aimed at simplifying the use of Noise2Void and its many 
    variants and cousins (CARE, Noise2Noise, N2V2, P(P)N2V, HDN, MicroSplit etc.).
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/CAREamics/careamics
  doc_url: https://careamics.github.io
  doc_source_url: https://github.com/CAREamics/careamics.github.io

extra:
  recipe-maintainers:
    - jdeschamps
